[163]
source          = imap+insecure://zzr211001@163.com@127.0.0.1:11143
source-cred-cmd = cat /home/feisama/Documents/mail-keys/163-mail-keys
outgoing        = smtps://zzr211001@163.com@smtp.163.com:465
outgoing-cred-cmd = cat /home/feisama/Documents/mail-keys/163-mail-keys
from            = zzr211001@163.com

[Gmail]
source          = imaps://zzr211001@gmail.com@imap.gmail.com:993
source-cred-cmd = cat /home/feisama/Documents/mail-keys/gmail-keys-for-aerc
outgoing        = smtps://zzr211001@gmail.com@smtp.gmail.com:465
outgoing-cred-cmd = cat /home/feisama/Documents/mail-keys/gmail-keys-for-aerc
from            = zzr211001@gmail.com
